source 'https://gitlab.rambler.ru/cocoapods/cocoapods.git'
source 'https://github.com/cocoapods/Specs.git'

inhibit_all_warnings!

platform :ios, '7.0'

pod 'Typhoon', '~> 3.3'
pod 'ViperMcFlurry', :git => 'https://gitlab.rambler.ru/cocoapods/VIPERMcFlurry.git', :branch => 'feature/ModuleInputOutput'

target 'GenerambaSandboxTests' do
    pod 'OCMock', '~>3.1'
    pod 'RamblerMcFlurry/Testing'
end
