source 'https://gitlab.rambler.ru/cocoapods/cocoapods.git'
source 'https://github.com/cocoapods/Specs.git'

inhibit_all_warnings!

platform :ios, '7.0'

pod 'Typhoon', '~> 3.3'
pod 'ViperMcFlurry', '~> 1.1'
pod 'RamblerTyphoonUtils/AssemblyCollector', '~> 1.0'

target 'GenerambaSandboxTests' do
    pod 'OCMock', '~>3.1'
    pod 'RamblerTyphoonUtils/AssemblyTesting', '~> 1.0'
end
